name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'new feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'dependencies'
      - 'documentation'
      - 'clean code'
      - 'CI/CD'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
      - 'new feature'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
      - 'dependencies'
  default: patch
template: |
  ## Changelog

  $CHANGES
