version: "2.4"
services:
  mqtt-server:
    # user: testuser
    # password: secret
    container_name: rika2mqtt_mqtt-server
    image: eclipse-mosquitto
    volumes:
      - type: bind
        source: ./mosquitto/config/
        target: /mosquitto/config/
    ports:
      - 1883:1883

#  rika2mqtt:
#    container_name: rika2mqtt_bridge
#    depends_on:
#      - mqtt-server
#    image: cookiecodedev/rika2mqtt
#    environment:
#      - MQTT_HOST=mqtt-server
#      - MQTT_USERNAME=testuser
#      - MQTT_PASSWORD=secret
#      - RIKA_EMAIL=<your email>
#      - RIKA_PASSWORD=<your password>
#optional properties
#      - MQTT_URI_SCHEME=tcp://
#      - MQTT_PORT=1883
#      - MQTT_COMMAND_TOPIC_NAME=cmnd/rika2mqtt
#      - MQTT_TELEMETRY_REPORT_TOPIC_NAME=tele/rika2mqtt


  influxdb:
    container_name: influxdb
    image: influxdb:2.7
    ports:
      - 8086:8086
#    volumes:
#    - $PWD/data:/var/lib/influxdb2
#    - $PWD/config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminadmin
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_BUCKET=rika2mqtt
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=admin-token

volumes:
  data:
    name: "mqtt-broker-data"
