server:
  port: 9009
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: "Rika2Mqtt"

rika:
  email:
  password:
  keepAliveTimeout: PT60S
mqtt:
  host:
  user:
  password:
bridge:
  reportInterval: PT60S
