rika:
  email: ${RIKA_EMAIL}
  password: ${RIKA_PASSWORD}
  keepAliveTimeout: PT60S
mqtt:
  host: ${MQTT_HOST}
  username: ${MQTT_USERNAME}
  password: ${MQTT_PASSWORD}
  telemetry-report-topic-name: ${MQTT_TELEMETRY_REPORT_TOPIC_NAME}
  command-topic-name: ${MQTT_COMMAND_TOPIC_NAME}
bridge:
  reportInterval: PT60S
