import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  // tutorialSidebar: [
  //   'intro',
  //   // 'hello',
  //   // {
  //   //   type: 'category',
  //   //   label: 'Tutorial',
  //   //   items: ['tutorial-basics/create-a-document'],
  //   // },
  // ],

  // "sidebar": [
  //   ["Getting Started", [
  //     ["Overview", "/"],
  //     ["Getting Started", "/getting-started"],
  //     ["Configuration", "/configuration"],
  //     ["Plugin development", "/write-a-plugin"]
  //   ]],
  //   ["Examples", [
  //     ["Publish stove status to MQTT", "/example-telemetry-mqtt"],
  //     ["Control RIKA stove via MQTT", "/example-command-mqtt"]
  //   ]],
  //   ["Misc.", [
  //     ["Contributing", "/contributing"],
  //     ["Stack", "/stack"]
  //   ]]
  // ],

};

export default sidebars;
