name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SOME_DUMMY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

        #something
